import type { Metadata } from "next";
import { Poppins,} from "next/font/google";
import "./globals.css";

const popins = Poppins({
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  adjustFontFallback: true,
  style: ["normal", "italic"],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="">
      <body
        className={`${popins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
