import Menu from "@/component/auth/dashboard/Menu";
import type { Metadata } from "next";
import { Poppins,} from "next/font/google";


const popins = Poppins({
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
  adjustFontFallback: true,
  style: ["normal", "italic"],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="">
      
      <body
        className={`${popins.className}`}
      >
        {/* dashboard */}
        <div>
          <div className="dashboard-background min-h-[300px]">
            {/* menu */}
            <Menu></Menu>
          </div>
          {/* children */}
          <div>
          {children}
          </div>
        </div>
      </body>
      
    </html>
  );
}
